const question = document. querySelector('#question')
const choices = document. querySelectorAll('.choice-text')
const question = document. querySelector('#question')
const question = document. querySelector('#question')
const question = document. querySelector('#question')